steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - staking-efficiency-alt-indexer
      - --region=europe-west3
      - --source=.
      - --trigger-http
      - --allow-unauthenticated
      - --runtime=nodejs14
      - --timeout=540s
